FROM python:3.7

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code

# Install packages
RUN apt update && apt install netcat -y
RUN pip install pipenv
COPY Pipfile Pipfile.lock /code/
RUN pipenv install --system

COPY ./docker-entrypoint.dev.sh /code/docker-entrypoint.dev.sh

ENTRYPOINT ["/code/docker-entrypoint.dev.sh"]