# Generated by Django 3.0.4 on 2020-03-17 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0003_auto_20200317_2240'),
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='_host',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='_host',
        ),
        migrations.AddField(
            model_name='event',
            name='_hosts',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='_is_zoom_meeting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventappointment',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventappointment',
            name='zoom_meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoom.ZoomMeeting'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='_hosts',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='_is_zoom_meeting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capaciteit per Host'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capaciteit per Host'),
        ),
    ]
