# Generated by Django 2.2.6 on 2019-10-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20191009_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmoment',
            name='allowed_tests',
            field=models.ManyToManyField(to='planner.Test'),
        ),
    ]
