# Generated by Django 2.2.6 on 2019-10-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_testmoment_allowed_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmoment',
            name='allowed_tests',
        ),
        migrations.AddField(
            model_name='coursemoment',
            name='allowed_tests',
            field=models.ManyToManyField(to='planner.Test', verbose_name='Toetsjes'),
        ),
        migrations.AlterField(
            model_name='testmoment',
            name='hidden_from_total',
            field=models.BooleanField(default=False, verbose_name='Verborgen'),
        ),
    ]
