# Generated by Django 2.2.6 on 2019-10-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20191011_1834'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemoment',
            unique_together={('course', 'time_slot')},
        ),
    ]
