# Generated by Django 2.2.6 on 2019-10-26 13:01

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20191019_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_secret',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=64),
        ),
    ]
