# Generated by Django 2.2.6 on 2019-10-26 13:03

from django.db import migrations, models
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_appointment_cancel_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cancel_secret',
            field=models.CharField(default=planner.models.get_cancel_secret, max_length=64),
        ),
    ]
