# Generated by Django 2.2.6 on 2019-11-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_testmoment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemoment',
            name='predetermined_tests',
            field=models.BooleanField(default=False, verbose_name='Vooraf bepaalde toetsjes'),
        ),
    ]
