# Generated by Django 2.2.6 on 2019-11-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_coursemoment_predetermined_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemoment',
            name='predetermined_tests',
        ),
        migrations.AlterUniqueTogether(
            name='testmoment',
            unique_together={('start_time', 'end_time', 'location', 'date')},
        ),
    ]
