# Generated by Django 2.2.6 on 2019-11-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20191106_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemoment',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Beschrijving'),
        ),
    ]
