# Generated by Django 2.2.7 on 2019-11-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20191118_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmoment',
            options={'ordering': ('-date', 'start_time'), 'verbose_name': 'Toetsmoment', 'verbose_name_plural': 'Toetsmomenten'},
        ),
        migrations.AddField(
            model_name='testmoment',
            name='max_tests',
            field=models.IntegerField(default=3, verbose_name='Aantal toetsjes'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Naam'),
        ),
    ]
