# Generated by Django 2.2.7 on 2020-01-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_nontestmoment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseMoment',
            new_name='CourseMomentRelation',
        ),
    ]
