# Generated by Django 3.0.2 on 2020-01-14 09:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_auto_20200114_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availibility',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
