# Generated by Django 3.0.2 on 2020-01-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_eventtype_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Availibility',
            new_name='Availability',
        ),
    ]
