# Generated by Django 3.0.2 on 2020-01-14 11:50

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_auto_20200114_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_slot_length', models.IntegerField(blank=True, null=True)),
                ('_location', models.CharField(blank=True, max_length=16, null=True)),
                ('_extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planner.EventType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
