# Generated by Django 3.0.2 on 2020-01-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0025_auto_20200128_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='slug',
            new_name='uuid',
        ),
    ]
