# Generated by Django 3.0.2 on 2020-01-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0026_auto_20200128_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventappointment',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
