# Generated by Django 3.0.2 on 2020-01-29 13:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0027_eventappointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventappointment',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventappointment',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='eventappointment',
            name='student_nr',
            field=models.PositiveIntegerField(verbose_name='Studentnummer'),
        ),
    ]
