# Generated by Django 3.0.2 on 2020-01-29 13:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0028_auto_20200129_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventappointment',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
