# Generated by Django 3.0.2 on 2020-01-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0030_auto_20200129_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventappointment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='planner.Event'),
        ),
    ]
