# Generated by Django 3.0.2 on 2020-02-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0031_auto_20200129_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capaciteit'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capaciteit'),
        ),
    ]
