# Generated by Django 3.0.3 on 2020-02-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0032_auto_20200216_1336'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventappointment',
            unique_together={('student_nr', 'date')},
        ),
    ]
