# Generated by Django 3.0.3 on 2020-02-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0033_auto_20200217_1508'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemomentrelation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursemomentrelation',
            name='allowed_tests',
        ),
        migrations.RemoveField(
            model_name='coursemomentrelation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursemomentrelation',
            name='time_slot',
        ),
        migrations.AlterUniqueTogether(
            name='testmoment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testmoment',
            name='courses',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseMomentRelation',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestMoment',
        ),
    ]
