# Generated by Django 3.0.3 on 2020-02-20 13:28

from django.db import migrations, models
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0034_auto_20200220_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventappointment',
            name='cancel_secret',
            field=models.CharField(default=planner.models.get_cancel_secret, max_length=64),
        ),
    ]
