# Generated by Django 3.0.3 on 2020-02-22 16:41

from django.db import migrations, models
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0035_eventappointment_cancel_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventappointment',
            name='cancel_secret',
            field=models.CharField(default=planner.models.get_cancel_secret, max_length=64, unique=True),
        ),
    ]
