# Generated by Django 3.0.3 on 2020-02-27 13:26

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0035_eventappointment_cancel_secret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-_start_time']},
        ),
        migrations.AlterModelOptions(
            name='eventappointment',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='_end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='_start_time',
        ),
        migrations.AlterField(
            model_name='eventappointment',
            name='cancel_secret',
            field=models.CharField(default=planner.models.get_cancel_secret, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='EventSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_slot_length', models.IntegerField(blank=True, null=True)),
                ('_location', models.CharField(blank=True, max_length=16, null=True)),
                ('_extras', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capaciteit')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Tijd')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Start Tijd')),
                ('_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='planner.EventType')),
            ],
            options={
                'verbose_name': 'Event Reeks',
                'verbose_name_plural': 'Event Reeksen',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_sequence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planner.EventSequence'),
            preserve_default=False,
        ),
    ]
