# Generated by Django 3.0.4 on 2020-03-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_auto_20200316_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='oauth2token',
            options={'verbose_name': 'OAuth2 Token', 'verbose_name_plural': 'OAuth2 Tokens'},
        ),
    ]
