# Generated by Django 2.2.5 on 2019-10-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmoment',
            name='courses',
            field=models.ManyToManyField(related_name='test_moments', through='planner.CourseMoment', to='planner.Course', verbose_name='Vakken'),
        ),
    ]
