# Generated by Django 2.2.6 on 2019-10-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20191008_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='student_nr',
            field=models.IntegerField(null=True, verbose_name='Studentnummer'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('student_nr', 'date')},
        ),
    ]
