# Generated by Django 2.2.5 on 2019-09-28 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20190927_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Afspraak', 'verbose_name_plural': 'Afspraken'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Vak', 'verbose_name_plural': 'Vakken'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Toetsje', 'verbose_name_plural': 'Toetsjes'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Tijdslot', 'verbose_name_plural': 'Tijdslots'},
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='slot_length',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='test_length',
            field=models.IntegerField(default=15, verbose_name='Toetslengte'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Course', verbose_name='Vak'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(verbose_name='Lengte'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(verbose_name='Begintijd'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student_name',
            field=models.CharField(max_length=32, verbose_name='Naam'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tests',
            field=models.ManyToManyField(to='planner.Test', verbose_name='Toetjes'),
        ),
        migrations.AlterField(
            model_name='coursetimeslotmember',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Course', verbose_name='Vak'),
        ),
        migrations.AlterField(
            model_name='coursetimeslotmember',
            name='places',
            field=models.IntegerField(verbose_name='Plekken'),
        ),
        migrations.AlterField(
            model_name='coursetimeslotmember',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.TimeSlot', verbose_name='Tijdsslot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='courses',
            field=models.ManyToManyField(related_name='timeslots', through='planner.CourseTimeSlotMember', to='planner.Course', verbose_name='Vakken'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(verbose_name='Eindtijd'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='location',
            field=models.CharField(max_length=16, verbose_name='Locatie'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(verbose_name='Begintijd'),
        ),
    ]
